table Mapping_Specialty
	lineageTag: 209e7783-5846-49f0-9f27-45c0a7c20cd0

	column Specialty
		dataType: string
		lineageTag: ee051c35-44ec-4b8a-bd6d-0608c0bbf62a
		summarizeBy: none
		sourceColumn: Specialty

		annotation SummarizationSetBy = Automatic

	column 'Specialty Group'
		dataType: string
		lineageTag: 4b9af104-d615-4dd4-bf3e-7edfdb2d266e
		summarizeBy: none
		sourceColumn: Specialty Group

		annotation SummarizationSetBy = Automatic

	partition Mapping_Specialty = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\matsi\EDA Projects\Data-Mapping-Bg\Data\Mapping_Specialty.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Column1", type text}, {"Column2", type text}}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Tipo Alterado", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Specialty", type text}, {"Specialty Group", type text}})
				in
				    #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

